version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: delic_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data # Persistência dos dados do DB
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app # Mapeia o código fonte para dentro do container
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/delic_db
      OPENAI_API_KEY: ${OPENAI_API_KEY} # Pega do .env da raiz
      # GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend:/app # Mapeia o código fonte para dentro do container
    ports:
      - "5173:5173"
    depends_on:
      - backend